//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaPortfolyoProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int AboutID { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Email { get; set; }
        public string Freelance { get; set; }
        public string Decription1 { get; set; }
        public string Decription2 { get; set; }
        public string Degree { get; set; }
    }
}
